Changed api call to DB retrieval
racker/salus-telemetry-agent-catalog-management pull request #43
Opened 2020-09-09 12:35 UTC by rohitsngh27

# Resolves
https://jira.rax.io/browse/SALUS-1014

# What
Changed api call to DB retrieval where possible

# How
Created a method to get from DB and convert it to DTO

## How to test
This can be tested via unit test

2020-09-09 16:15 UTC, itzg submitted a review, later dismissed
Looks good, but probably good to wait on one more approval.

2020-09-09 17:46 UTC, jjbuchan reviewed
Since you've removed the ApiClient you can also remove the section in the `pom.xml` relating to that.

That and the usual `Optional` change will make this complete.

2020-09-09 17:49 UTC, jjbuchan commented
I just realized you might also be able to remove some of the API Client dependencies in other PRs as well.  Anywhere an API Client is no longer used we should be able to clean up the pom.

2020-09-09 17:52 UTC, rohitsngh27 commented
> I just realized you might also be able to remove some of the API Client dependencies in other PRs as well. Anywhere an API Client is no longer used we should be able to clean up the pom.

There's a resourceApi request for **getResourcesWithLabels** which is being used, That's why i didn't remove it from the pom.xml

2020-09-09 17:57 UTC, jjbuchan commented
There's two different client pieces to the pom.  In this case I initially meant we can remove this part that builds/exports the api client module.

```
      <plugin>
        <artifactId>maven-jar-plugin</artifactId>
        <version>3.0.2</version>
        <executions>
          <execution>
            <id>client-jar</id>
            <goals><goal>jar</goal></goals>
            <configuration>
              <classifier>client</classifier>
              <includes>
                <include>**/web/client/**</include>
                <include>**/web/model/**</include>
              </includes>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

but for the other PRs I do mean that we should remove dependencies wherever possible too.  Thanks for already checking that here.

2020-09-10 17:41 UTC, itzg reviewed
Changes look ok other than possibly still needing pom change.

2020-09-10 17:41 UTC, itzg commented on pom.xml
>              </configuration>
I think @jjbuchan 's [comment](https://github.com/racker/salus-telemetry-agent-catalog-management/pull/43#issuecomment-689723219) was asking to remove this entire `client-jar` execution.

2020-09-10 17:45 UTC, rohitsngh27 commented on pom.xml
>              </configuration>
I think we still need model jar for ResourceDTO object which is in resource management web/model package

2020-09-10 18:27 UTC, jjbuchan requested changes

2020-09-10 18:27 UTC, jjbuchan commented on pom.xml
>              </configuration>
This block is not related to Resources.  This is the client jar that can be imported by other applications.  It was previously only used by ambassador but you should be removing that now.

2020-09-10 18:31 UTC, jjbuchan approved these changes

2020-09-10 18:33 UTC, itzg approved these changes

2020-09-10 18:36 UTC, merged